apiVersion: v1
kind: ConfigMap
metadata:
  name: quantummesh-config
  namespace: quantummesh
data:
  EUREKA_URL: "http://discovery-service:8761/eureka/"
  CONFIG_SERVER_URL: "http://config-server:8888"
  KAFKA_BOOTSTRAP: "kafka:9092"
  AI_ENGINE_HOST: "ai-engine"
---
apiVersion: v1
kind: Secret
metadata:
  name: quantummesh-secrets
  namespace: quantummesh
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_ME_BEFORE_APPLY"
  DB_USER: "REPLACE_ME_BEFORE_APPLY"
  DB_PASSWORD: "REPLACE_ME_BEFORE_APPLY"
