apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: quantummesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery
          image: quantummesh/discovery-service:1.0.0
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_HOSTNAME
              value: discovery-service
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: quantummesh
spec:
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
