apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quantummesh-ingress
  namespace: quantummesh
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  rules:
    - host: quantummesh.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
